version: "3.9"

services:
  seigaiha:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-10000}
        GID: ${GID:-10001}
    user: "${UID:-10000}:${GID:-10001}"
    restart: "no"
    volumes:
      - .:/app
      - ./output:/output
