version: '3'

vars:
  SERVICE: seigaiha

env:
  UID:
    sh: id -u
  GID:
    sh: id -g

tasks:
  default:
    cmds:
      - task --list

  # Application
  run:
    desc: Create Seigaiha pattern from JSON preset file or string
    vars:
      PRESET: '{{.p | default "default.json"}}'
    cmds:
      - docker compose run --rm {{.SERVICE}} python main.py -p '{{.PRESET}}'

  # Docker
  up:
    desc: Up service
    cmds:
      - docker compose up -d {{.CLI_ARGS | default "--build --remove-orphans --force-recreate"}}

  down:
    desc: Down service
    cmds:
      - docker compose down {{.CLI_ARGS | default "--rmi local --remove-orphans"}}

  # Tools
  contribute:
    desc: Tasks for contributing
    cmds:
      - task: tools:pylint
      - task: tools:pycodestyle

  tools:pylint:
    desc: Run pylint
    cmds:
      - docker compose run --rm {{.SERVICE}} pylint --max-line-length=120 --recursive=y .

  tools:pycodestyle:
    desc: Run pycodestyle
    cmds:
      - docker compose run --rm {{.SERVICE}} pycodestyle --max-line-length=120 --show-source .

  tools:black:check:
    desc: Run black dryrun
    cmds:
      - docker compose run --rm {{.SERVICE}} black . --diff --color

  tools:black:fix:
    desc: Run black
    cmds:
      - docker compose run --rm {{.SERVICE}} black .
