name: Pylint

on: [ push ]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - run: pip install pylint -r requirements.txt
      - run: pylint **/*.py